export const RULE_TYPES = Object.freeze({
  INPUT_AND_ASSERT: "INPUT_AND_ASSERT",
  CLICK_AND_ASSERT: "CLICK_AND_ASSERT",
  TAG_EXISTS: "TAG_EXISTS",
  TAG_NOT_EXISTS: "TAG_NOT_EXISTS",
  TAG_COUNT: "TAG_COUNT",
  TEXT_EQUALS: "TEXT_EQUALS",
  TEXT_CONTAINS: "TEXT_CONTAINS",
  JS_CODE_EXCLUDES: "JS_CODE_EXCLUDES",
  JS_CODE_INCLUDES: "JS_CODE_INCLUDES",
  CONSOLE_LOG_CONTAINS: "CONSOLE_LOG_CONTAINS",
  CONSOLE_NO_ERRORS: "CONSOLE_NO_ERRORS",
  CSS_PROP_EXISTS: "CSS_PROP_EXISTS",
  CSS_PROP_NOT_VALUE: "CSS_PROP_NOT_VALUE",
  CSS_CODE_INCLUDES: "CSS_CODE_INCLUDES"
});

export const RULE_TYPE_OPTIONS = Object.freeze(Object.values(RULE_TYPES));
